version: '3.4'

services:
  backroll.telegram:
    image: ${DOCKER_REGISTRY-}backrolltelegram
    build:
      context: .
      dockerfile: src/BackRoll.Telegram/Dockerfile
      args:
        Spotify__ClientId: ${SPOTIFY_CLIENTID}
        Spotify__ClientSecret: ${SPOTIFY_CLIENTSECRET}
        YandexMusic__UseProxy: ${YANDEXMUSIC_USEPROXY}
        YandexMusic__ProxyHost: ${YANDEXMUSIC_PROXYHOST}
        YandexMusic__ProxyPort: ${YANDEXMUSIC_PROXYPORT}
        YandexMusic__ProxyUserName: ${YANDEXMUSIC_PROXYUSERNAME}
        YandexMusic__ProxyPassword: ${YANDEXMUSIC_PROXYPASSWORD}
    environment:
      - APPINSIGHTS_CONNECTIONSTRING=${APPINSIGHTS_CONNECTIONSTRING}
      - Spotify__ClientId=${SPOTIFY_CLIENTID}
      - Spotify__ClientSecret=${SPOTIFY_CLIENTSECRET}
      - YandexMusic__UseProxy=${YANDEXMUSIC_USEPROXY}
      - YandexMusic__ProxyHost=${YANDEXMUSIC_PROXYHOST}
      - YandexMusic__ProxyPort=${YANDEXMUSIC_PROXYPORT}
      - YandexMusic__ProxyUserName=${YANDEXMUSIC_PROXYUSERNAME}
      - YandexMusic__ProxyPassword=${YANDEXMUSIC_PROXYPASSWORD}
      - TelegramBot__Secret=${TELEGRAMBOT_SECRET}
      - TelegramBot__DbConnectionString=${TELEGRAMBOT_DBCONNECTIONSTRING}
    volumes:
      - ./data:/app/data
